# Generated by Django 5.1.6 on 2025-03-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Ingredient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
